#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: meson
# autospec version: v21
# autospec commit: fbbd4e3
#
Name     : gnome-mahjongg
Version  : 47.2
Release  : 19
URL      : https://download.gnome.org/sources/gnome-mahjongg/47/gnome-mahjongg-47.2.tar.xz
Source0  : https://download.gnome.org/sources/gnome-mahjongg/47/gnome-mahjongg-47.2.tar.xz
Summary  : No detailed summary available
Group    : Development/Tools
License  : CC-BY-SA-3.0 GPL-2.0
Requires: gnome-mahjongg-bin = %{version}-%{release}
Requires: gnome-mahjongg-data = %{version}-%{release}
Requires: gnome-mahjongg-license = %{version}-%{release}
Requires: gnome-mahjongg-locales = %{version}-%{release}
Requires: gnome-mahjongg-man = %{version}-%{release}
BuildRequires : buildreq-gnome
BuildRequires : buildreq-meson
BuildRequires : librsvg-dev
BuildRequires : pkgconfig(libadwaita-1)
BuildRequires : pkgconfig(librsvg-2.0)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
# Mahjongg
Single-player tile-matching game, commonly known as Mahjong solitaire.

%package bin
Summary: bin components for the gnome-mahjongg package.
Group: Binaries
Requires: gnome-mahjongg-data = %{version}-%{release}
Requires: gnome-mahjongg-license = %{version}-%{release}

%description bin
bin components for the gnome-mahjongg package.


%package data
Summary: data components for the gnome-mahjongg package.
Group: Data

%description data
data components for the gnome-mahjongg package.


%package doc
Summary: doc components for the gnome-mahjongg package.
Group: Documentation
Requires: gnome-mahjongg-man = %{version}-%{release}

%description doc
doc components for the gnome-mahjongg package.


%package license
Summary: license components for the gnome-mahjongg package.
Group: Default

%description license
license components for the gnome-mahjongg package.


%package locales
Summary: locales components for the gnome-mahjongg package.
Group: Default

%description locales
locales components for the gnome-mahjongg package.


%package man
Summary: man components for the gnome-mahjongg package.
Group: Default

%description man
man components for the gnome-mahjongg package.


%prep
%setup -q -n gnome-mahjongg-47.2
cd %{_builddir}/gnome-mahjongg-47.2
pushd ..
cp -a gnome-mahjongg-47.2 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1740499546
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
meson --libdir=lib64 --prefix=/usr --buildtype=plain   builddir
ninja -v -C builddir
GOAMD64=v3
CFLAGS="$CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 " CXXFLAGS="$CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 " LDFLAGS="$LDFLAGS -march=x86-64-v3 " meson --libdir=lib64 --prefix=/usr --buildtype=plain   builddiravx2
ninja -v -C builddiravx2

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
mkdir -p %{buildroot}/usr/share/package-licenses/gnome-mahjongg
cp %{_builddir}/gnome-mahjongg-%{version}/COPYING %{buildroot}/usr/share/package-licenses/gnome-mahjongg/4cc77b90af91e615a64ae04893fdffa7939db84c || :
cp %{_builddir}/gnome-mahjongg-%{version}/help/C/license.page %{buildroot}/usr/share/package-licenses/gnome-mahjongg/99449fd3e6417f1f32dbe2a5b252880badb25704 || :
GOAMD64=v3
DESTDIR=%{buildroot}-v3 ninja -C builddiravx2 install
GOAMD64=v2
DESTDIR=%{buildroot} ninja -C builddir install
%find_lang gnome-mahjongg
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/V3/usr/bin/gnome-mahjongg
/usr/bin/gnome-mahjongg

%files data
%defattr(-,root,root,-)
/usr/share/applications/org.gnome.Mahjongg.desktop
/usr/share/dbus-1/services/org.gnome.Mahjongg.service
/usr/share/glib-2.0/schemas/org.gnome.Mahjongg.gschema.xml
/usr/share/gnome-mahjongg/maps/mahjongg.map
/usr/share/gnome-mahjongg/themes/educational.png
/usr/share/gnome-mahjongg/themes/postmodern.svg
/usr/share/gnome-mahjongg/themes/smooth.png
/usr/share/icons/hicolor/scalable/apps/org.gnome.Mahjongg.svg
/usr/share/icons/hicolor/symbolic/apps/org.gnome.Mahjongg-symbolic.svg
/usr/share/metainfo/org.gnome.Mahjongg.metainfo.xml

%files doc
%defattr(0644,root,root,0755)
/usr/share/help/C/gnome-mahjongg/figures/hints-video.ogv
/usr/share/help/C/gnome-mahjongg/figures/mahjongg-video.ogv
/usr/share/help/C/gnome-mahjongg/figures/org.gnome.Mahjongg.svg
/usr/share/help/C/gnome-mahjongg/gameplay.page
/usr/share/help/C/gnome-mahjongg/hints.page
/usr/share/help/C/gnome-mahjongg/index.page
/usr/share/help/C/gnome-mahjongg/legal.xml
/usr/share/help/C/gnome-mahjongg/license.page
/usr/share/help/C/gnome-mahjongg/moves.page
/usr/share/help/C/gnome-mahjongg/pause.page
/usr/share/help/C/gnome-mahjongg/rules.page
/usr/share/help/C/gnome-mahjongg/scoring.page
/usr/share/help/C/gnome-mahjongg/strategy.page
/usr/share/help/ca/gnome-mahjongg/figures/hints-video.ogv
/usr/share/help/ca/gnome-mahjongg/figures/mahjongg-video.ogv
/usr/share/help/ca/gnome-mahjongg/figures/org.gnome.Mahjongg.svg
/usr/share/help/ca/gnome-mahjongg/gameplay.page
/usr/share/help/ca/gnome-mahjongg/hints.page
/usr/share/help/ca/gnome-mahjongg/index.page
/usr/share/help/ca/gnome-mahjongg/legal.xml
/usr/share/help/ca/gnome-mahjongg/license.page
/usr/share/help/ca/gnome-mahjongg/moves.page
/usr/share/help/ca/gnome-mahjongg/pause.page
/usr/share/help/ca/gnome-mahjongg/rules.page
/usr/share/help/ca/gnome-mahjongg/scoring.page
/usr/share/help/ca/gnome-mahjongg/strategy.page
/usr/share/help/cs/gnome-mahjongg/figures/hints-video.ogv
/usr/share/help/cs/gnome-mahjongg/figures/mahjongg-video.ogv
/usr/share/help/cs/gnome-mahjongg/figures/org.gnome.Mahjongg.svg
/usr/share/help/cs/gnome-mahjongg/gameplay.page
/usr/share/help/cs/gnome-mahjongg/hints.page
/usr/share/help/cs/gnome-mahjongg/index.page
/usr/share/help/cs/gnome-mahjongg/legal.xml
/usr/share/help/cs/gnome-mahjongg/license.page
/usr/share/help/cs/gnome-mahjongg/moves.page
/usr/share/help/cs/gnome-mahjongg/pause.page
/usr/share/help/cs/gnome-mahjongg/rules.page
/usr/share/help/cs/gnome-mahjongg/scoring.page
/usr/share/help/cs/gnome-mahjongg/strategy.page
/usr/share/help/da/gnome-mahjongg/figures/hints-video.ogv
/usr/share/help/da/gnome-mahjongg/figures/mahjongg-video.ogv
/usr/share/help/da/gnome-mahjongg/figures/org.gnome.Mahjongg.svg
/usr/share/help/da/gnome-mahjongg/gameplay.page
/usr/share/help/da/gnome-mahjongg/hints.page
/usr/share/help/da/gnome-mahjongg/index.page
/usr/share/help/da/gnome-mahjongg/legal.xml
/usr/share/help/da/gnome-mahjongg/license.page
/usr/share/help/da/gnome-mahjongg/moves.page
/usr/share/help/da/gnome-mahjongg/pause.page
/usr/share/help/da/gnome-mahjongg/rules.page
/usr/share/help/da/gnome-mahjongg/scoring.page
/usr/share/help/da/gnome-mahjongg/strategy.page
/usr/share/help/de/gnome-mahjongg/figures/hints-video.ogv
/usr/share/help/de/gnome-mahjongg/figures/mahjongg-video.ogv
/usr/share/help/de/gnome-mahjongg/figures/org.gnome.Mahjongg.svg
/usr/share/help/de/gnome-mahjongg/gameplay.page
/usr/share/help/de/gnome-mahjongg/hints.page
/usr/share/help/de/gnome-mahjongg/index.page
/usr/share/help/de/gnome-mahjongg/legal.xml
/usr/share/help/de/gnome-mahjongg/license.page
/usr/share/help/de/gnome-mahjongg/moves.page
/usr/share/help/de/gnome-mahjongg/pause.page
/usr/share/help/de/gnome-mahjongg/rules.page
/usr/share/help/de/gnome-mahjongg/scoring.page
/usr/share/help/de/gnome-mahjongg/strategy.page
/usr/share/help/el/gnome-mahjongg/figures/hints-video.ogv
/usr/share/help/el/gnome-mahjongg/figures/mahjongg-video.ogv
/usr/share/help/el/gnome-mahjongg/figures/org.gnome.Mahjongg.svg
/usr/share/help/el/gnome-mahjongg/gameplay.page
/usr/share/help/el/gnome-mahjongg/hints.page
/usr/share/help/el/gnome-mahjongg/index.page
/usr/share/help/el/gnome-mahjongg/legal.xml
/usr/share/help/el/gnome-mahjongg/license.page
/usr/share/help/el/gnome-mahjongg/moves.page
/usr/share/help/el/gnome-mahjongg/pause.page
/usr/share/help/el/gnome-mahjongg/rules.page
/usr/share/help/el/gnome-mahjongg/scoring.page
/usr/share/help/el/gnome-mahjongg/strategy.page
/usr/share/help/es/gnome-mahjongg/figures/hints-video.ogv
/usr/share/help/es/gnome-mahjongg/figures/mahjongg-video.ogv
/usr/share/help/es/gnome-mahjongg/figures/org.gnome.Mahjongg.svg
/usr/share/help/es/gnome-mahjongg/gameplay.page
/usr/share/help/es/gnome-mahjongg/hints.page
/usr/share/help/es/gnome-mahjongg/index.page
/usr/share/help/es/gnome-mahjongg/legal.xml
/usr/share/help/es/gnome-mahjongg/license.page
/usr/share/help/es/gnome-mahjongg/moves.page
/usr/share/help/es/gnome-mahjongg/pause.page
/usr/share/help/es/gnome-mahjongg/rules.page
/usr/share/help/es/gnome-mahjongg/scoring.page
/usr/share/help/es/gnome-mahjongg/strategy.page
/usr/share/help/eu/gnome-mahjongg/figures/hints-video.ogv
/usr/share/help/eu/gnome-mahjongg/figures/mahjongg-video.ogv
/usr/share/help/eu/gnome-mahjongg/figures/org.gnome.Mahjongg.svg
/usr/share/help/eu/gnome-mahjongg/gameplay.page
/usr/share/help/eu/gnome-mahjongg/hints.page
/usr/share/help/eu/gnome-mahjongg/index.page
/usr/share/help/eu/gnome-mahjongg/legal.xml
/usr/share/help/eu/gnome-mahjongg/license.page
/usr/share/help/eu/gnome-mahjongg/moves.page
/usr/share/help/eu/gnome-mahjongg/pause.page
/usr/share/help/eu/gnome-mahjongg/rules.page
/usr/share/help/eu/gnome-mahjongg/scoring.page
/usr/share/help/eu/gnome-mahjongg/strategy.page
/usr/share/help/fr/gnome-mahjongg/figures/hints-video.ogv
/usr/share/help/fr/gnome-mahjongg/figures/mahjongg-video.ogv
/usr/share/help/fr/gnome-mahjongg/figures/org.gnome.Mahjongg.svg
/usr/share/help/fr/gnome-mahjongg/gameplay.page
/usr/share/help/fr/gnome-mahjongg/hints.page
/usr/share/help/fr/gnome-mahjongg/index.page
/usr/share/help/fr/gnome-mahjongg/legal.xml
/usr/share/help/fr/gnome-mahjongg/license.page
/usr/share/help/fr/gnome-mahjongg/moves.page
/usr/share/help/fr/gnome-mahjongg/pause.page
/usr/share/help/fr/gnome-mahjongg/rules.page
/usr/share/help/fr/gnome-mahjongg/scoring.page
/usr/share/help/fr/gnome-mahjongg/strategy.page
/usr/share/help/hu/gnome-mahjongg/figures/hints-video.ogv
/usr/share/help/hu/gnome-mahjongg/figures/mahjongg-video.ogv
/usr/share/help/hu/gnome-mahjongg/figures/org.gnome.Mahjongg.svg
/usr/share/help/hu/gnome-mahjongg/gameplay.page
/usr/share/help/hu/gnome-mahjongg/hints.page
/usr/share/help/hu/gnome-mahjongg/index.page
/usr/share/help/hu/gnome-mahjongg/legal.xml
/usr/share/help/hu/gnome-mahjongg/license.page
/usr/share/help/hu/gnome-mahjongg/moves.page
/usr/share/help/hu/gnome-mahjongg/pause.page
/usr/share/help/hu/gnome-mahjongg/rules.page
/usr/share/help/hu/gnome-mahjongg/scoring.page
/usr/share/help/hu/gnome-mahjongg/strategy.page
/usr/share/help/id/gnome-mahjongg/figures/hints-video.ogv
/usr/share/help/id/gnome-mahjongg/figures/mahjongg-video.ogv
/usr/share/help/id/gnome-mahjongg/figures/org.gnome.Mahjongg.svg
/usr/share/help/id/gnome-mahjongg/gameplay.page
/usr/share/help/id/gnome-mahjongg/hints.page
/usr/share/help/id/gnome-mahjongg/index.page
/usr/share/help/id/gnome-mahjongg/legal.xml
/usr/share/help/id/gnome-mahjongg/license.page
/usr/share/help/id/gnome-mahjongg/moves.page
/usr/share/help/id/gnome-mahjongg/pause.page
/usr/share/help/id/gnome-mahjongg/rules.page
/usr/share/help/id/gnome-mahjongg/scoring.page
/usr/share/help/id/gnome-mahjongg/strategy.page
/usr/share/help/ko/gnome-mahjongg/figures/hints-video.ogv
/usr/share/help/ko/gnome-mahjongg/figures/mahjongg-video.ogv
/usr/share/help/ko/gnome-mahjongg/figures/org.gnome.Mahjongg.svg
/usr/share/help/ko/gnome-mahjongg/gameplay.page
/usr/share/help/ko/gnome-mahjongg/hints.page
/usr/share/help/ko/gnome-mahjongg/index.page
/usr/share/help/ko/gnome-mahjongg/legal.xml
/usr/share/help/ko/gnome-mahjongg/license.page
/usr/share/help/ko/gnome-mahjongg/moves.page
/usr/share/help/ko/gnome-mahjongg/pause.page
/usr/share/help/ko/gnome-mahjongg/rules.page
/usr/share/help/ko/gnome-mahjongg/scoring.page
/usr/share/help/ko/gnome-mahjongg/strategy.page
/usr/share/help/pl/gnome-mahjongg/figures/hints-video.ogv
/usr/share/help/pl/gnome-mahjongg/figures/mahjongg-video.ogv
/usr/share/help/pl/gnome-mahjongg/figures/org.gnome.Mahjongg.svg
/usr/share/help/pl/gnome-mahjongg/gameplay.page
/usr/share/help/pl/gnome-mahjongg/hints.page
/usr/share/help/pl/gnome-mahjongg/index.page
/usr/share/help/pl/gnome-mahjongg/legal.xml
/usr/share/help/pl/gnome-mahjongg/license.page
/usr/share/help/pl/gnome-mahjongg/moves.page
/usr/share/help/pl/gnome-mahjongg/pause.page
/usr/share/help/pl/gnome-mahjongg/rules.page
/usr/share/help/pl/gnome-mahjongg/scoring.page
/usr/share/help/pl/gnome-mahjongg/strategy.page
/usr/share/help/pt_BR/gnome-mahjongg/figures/hints-video.ogv
/usr/share/help/pt_BR/gnome-mahjongg/figures/mahjongg-video.ogv
/usr/share/help/pt_BR/gnome-mahjongg/figures/org.gnome.Mahjongg.svg
/usr/share/help/pt_BR/gnome-mahjongg/gameplay.page
/usr/share/help/pt_BR/gnome-mahjongg/hints.page
/usr/share/help/pt_BR/gnome-mahjongg/index.page
/usr/share/help/pt_BR/gnome-mahjongg/legal.xml
/usr/share/help/pt_BR/gnome-mahjongg/license.page
/usr/share/help/pt_BR/gnome-mahjongg/moves.page
/usr/share/help/pt_BR/gnome-mahjongg/pause.page
/usr/share/help/pt_BR/gnome-mahjongg/rules.page
/usr/share/help/pt_BR/gnome-mahjongg/scoring.page
/usr/share/help/pt_BR/gnome-mahjongg/strategy.page
/usr/share/help/ro/gnome-mahjongg/figures/hints-video.ogv
/usr/share/help/ro/gnome-mahjongg/figures/mahjongg-video.ogv
/usr/share/help/ro/gnome-mahjongg/figures/org.gnome.Mahjongg.svg
/usr/share/help/ro/gnome-mahjongg/gameplay.page
/usr/share/help/ro/gnome-mahjongg/hints.page
/usr/share/help/ro/gnome-mahjongg/index.page
/usr/share/help/ro/gnome-mahjongg/legal.xml
/usr/share/help/ro/gnome-mahjongg/license.page
/usr/share/help/ro/gnome-mahjongg/moves.page
/usr/share/help/ro/gnome-mahjongg/pause.page
/usr/share/help/ro/gnome-mahjongg/rules.page
/usr/share/help/ro/gnome-mahjongg/scoring.page
/usr/share/help/ro/gnome-mahjongg/strategy.page
/usr/share/help/ru/gnome-mahjongg/figures/hints-video.ogv
/usr/share/help/ru/gnome-mahjongg/figures/mahjongg-video.ogv
/usr/share/help/ru/gnome-mahjongg/figures/org.gnome.Mahjongg.svg
/usr/share/help/ru/gnome-mahjongg/gameplay.page
/usr/share/help/ru/gnome-mahjongg/hints.page
/usr/share/help/ru/gnome-mahjongg/index.page
/usr/share/help/ru/gnome-mahjongg/legal.xml
/usr/share/help/ru/gnome-mahjongg/license.page
/usr/share/help/ru/gnome-mahjongg/moves.page
/usr/share/help/ru/gnome-mahjongg/pause.page
/usr/share/help/ru/gnome-mahjongg/rules.page
/usr/share/help/ru/gnome-mahjongg/scoring.page
/usr/share/help/ru/gnome-mahjongg/strategy.page
/usr/share/help/sv/gnome-mahjongg/figures/hints-video.ogv
/usr/share/help/sv/gnome-mahjongg/figures/mahjongg-video.ogv
/usr/share/help/sv/gnome-mahjongg/figures/org.gnome.Mahjongg.svg
/usr/share/help/sv/gnome-mahjongg/gameplay.page
/usr/share/help/sv/gnome-mahjongg/hints.page
/usr/share/help/sv/gnome-mahjongg/index.page
/usr/share/help/sv/gnome-mahjongg/legal.xml
/usr/share/help/sv/gnome-mahjongg/license.page
/usr/share/help/sv/gnome-mahjongg/moves.page
/usr/share/help/sv/gnome-mahjongg/pause.page
/usr/share/help/sv/gnome-mahjongg/rules.page
/usr/share/help/sv/gnome-mahjongg/scoring.page
/usr/share/help/sv/gnome-mahjongg/strategy.page
/usr/share/help/uk/gnome-mahjongg/figures/hints-video.ogv
/usr/share/help/uk/gnome-mahjongg/figures/mahjongg-video.ogv
/usr/share/help/uk/gnome-mahjongg/figures/org.gnome.Mahjongg.svg
/usr/share/help/uk/gnome-mahjongg/gameplay.page
/usr/share/help/uk/gnome-mahjongg/hints.page
/usr/share/help/uk/gnome-mahjongg/index.page
/usr/share/help/uk/gnome-mahjongg/legal.xml
/usr/share/help/uk/gnome-mahjongg/license.page
/usr/share/help/uk/gnome-mahjongg/moves.page
/usr/share/help/uk/gnome-mahjongg/pause.page
/usr/share/help/uk/gnome-mahjongg/rules.page
/usr/share/help/uk/gnome-mahjongg/scoring.page
/usr/share/help/uk/gnome-mahjongg/strategy.page

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/gnome-mahjongg/4cc77b90af91e615a64ae04893fdffa7939db84c
/usr/share/package-licenses/gnome-mahjongg/99449fd3e6417f1f32dbe2a5b252880badb25704

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man6/gnome-mahjongg.6

%files locales -f gnome-mahjongg.lang
%defattr(-,root,root,-)

